### ISSUE TITLE
XCTest 

### ISSUE THREAD

**Issue by santi-g-s** [delawaremathguy/ShoppingList15#1]
I have a general question about your approach to Core Data and MVVM.

How do you work with XCTest and the Persistence Controller context.

**Comment by delawaremathguy** [comment]
It's fair to say that ShoppingList15 does not (!)

I have used testing on a project only once, only to verify that certain computational routines were producing correct output for all possible inputs (albeit for a small universe of possibilities).  I think you imagine something more general, possibly even expending to UI testing. 

If I were interested in adding testing, I probably would start down this path:

- collect the class functions you find on Item and Location in a new, DataManager class to provide these functions
- let the DataManager create and own the PersistentStore, managing it as a private var
- instantiate the DataManager at the main level, in ShoppingListApp: App
- inject that DataManager into the MainView's environment (so, the DM would not be a global singleton)
- (i'd probably have to inject the DM's managedObjectContext as well, since @FetchRequests implicitly need a context, although I would not rule out using equivalent NSFetchedResultsControllers directly in the DM in place of having @FetchRequests in views)
- access the DM as needed throughout the app from the environment

That would allow you to test, because you'll be able to create a DM explicitly for testing on its own, perhaps with an in-memory store.

Feel free to add additional comments.

DMG

**Comment by delawaremathguy** [comment]
Santiago,

i have added a new branch to the project named "MVVM" which implements most of what's described above, although i went a little farther and

- removed all `@FetchRequest`s and now use `NSFetchedResultsController`s in the new `DataManager` class, so there is no need to inject a managedObjectContext into the environment.
- (*just because i could* ...) i took the opportunity to replace all the `.alert(item:)` and `.sheet(item:)` syntax with current iOS 15 modifiers, which very much simplifies the project.

there are still a few tweaks to add on MVVM (e.g., the Persistent store needs a few lines of code so that you can work with an in-memory store for testing).  stay tuned.

finally, i am undecided whether i will merge the MVVM branch into the master branch ... i may just leave both available and folks can pick whichever branch they want to play with.

**Comment by santi-g-s** [comment]
@delawaremathguy This is awesome. Really appreciate your work here. I've been curious about implementing some of [Donny Wals](https://www.donnywals.com/) more sophisticated core data stuff in SwiftUI and you seem to be heading in the right direction with the `NSFetchedResultsController`. Also I'm particularly interested in the possibility of SwiftUI only seing a struct representations of the core data items. Something about that just seems so perfect. I remember when I first looked into this I saw [this tutorial series](https://medium.com/swlh/using-core-data-in-your-swiftui-app-with-combine-mvvm-and-protocols-4577f44d240d) which tried something like that. Might be worth checking out. I'll keep tracking this, I've been keeping up to date with this project for the past few years, I really appreciate the exploration you've done.
